- hosts: all
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install monitoring packages
    apt:
      pkg:
      - htop
      - iftop
      - iotop
      - glances
      state: present

  - name: Remove root password
    replace:
      path: /etc/shadow
      regexp: "^root:[^:]+:"
      replace: "root:*:"

  - name: Make sudoers %sudo password-less
    lineinfile:
      path: /etc/sudoers
      regexp: '^[\t ]*%sudo'
      line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'

  - name: Create sudo group
    group:
      name: sudo
      state: present

  - name: Create feedc0de user
    user:
      name: feedc0de
      groups: sudo
      shell: /bin/bash
      state: present

  - name: Install glusterfs packages
    apt:
      pkg:
      - glusterfs-server
      state: present

  - name: Set authorized key for user feedc0de copying it from current user
    authorized_key:
      user: root
      state: present
      key: '{{ item }}'
    with_file:
      - public_cloud/feedc0de@blechkistn
      - public_cloud/feedc0de@flucky-server
      - public_cloud/feedc0de@kuischronk
      - public_cloud/feedc0de@virtual-linux
      - public_cloud/JuiceSSH

  - name: Set authorized key for user feedc0de copying it from current user
    authorized_key:
      user: feedc0de
      state: present
      key: '{{ item }}'
    with_file:
      - public_cloud/feedc0de@blechkistn
      - public_cloud/feedc0de@flucky-server
      - public_cloud/feedc0de@kuischronk
      - public_cloud/feedc0de@virtual-linux
      - public_cloud/JuiceSSH
